sudo: required
dist: trusty

env:
  - VARIANT=starter TARGET=centos7
  - VARIANT=starter-arbitrary-uid TARGET=centos7
  - VARIANT=starter-epel TARGET=centos7
  - VARIANT=starter-systemd TARGET=centos7
  - VARIANT=starter-nsswrapper TARGET=centos7
  - VARIANT=starter-api TARGET=centos7
  - VARIANT=starter-scratch TARGET=centos7
  - VARIANT=contrib/java/jre TARGET=centos7
  - VARIANT=contrib/java/sdk TARGET=centos7

services:
 - docker

addons:
  apt:
    packages:
    - nodejs

install:
  - npm install -g dockerfile_lint

before_script:
  - make lint -C ${VARIANT}

script:
  - make -C ${VARIANT} TARGET=${TARGET}
