version: "2"
services:
  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
   starter-apb:
     image: registry.access.redhat.com/rhel7 
     labels:
       name: "acme/starter-ansible"
       vendor: "Acme Corp"
       version: "3.2"
       release: "1"
       build-date: "2016-10-12T14:12:54.553894Z"
       url: "https://www.acme.io"
       summary: "Acme Corp's starter-ansible app"
       description: "starter-ansible app will do ....."
       run: 'docker run -tdi --name ${NAME} ${IMAGE}'
       io.k8s.description: "starter-ansible app will do ....."
       io.k8s.display-name: "starter-ansible app"
       io.openshift.expose-services: ""
       io.openshift.tags: "acme,starter-ansible,starter,epel,ansible"
     command: "tail -f /dev/null"
     dev_overrides:
       environment:
         - "DEBUG=1"
  
registries: 
    openshift:
        url: docker-registry-default.router.default.svc.cluster.local
        namespace: starter-apb
        
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx   
