version: "2"
settings:
  conductor_base: registry.access.redhat.com/rhel7
services:
  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
   starterapb:
     from: registry.access.redhat.com/rhel7
     roles:
     - starter-apb
     labels:
       name: "acme/starter-ansible"
       vendor: "Acme Corp"
       version: "3.2"
       release: "1"
       url: "https://www.acme.io"
       summary: "Acme Corp's starter-ansible app"
       description: "starter-ansible app will do ....."
       run: 'docker run -tdi --name ${NAME} ${IMAGE}'
       io.k8s.description: "starter-ansible app will do ....."
       io.k8s.display-name: "starter-ansible app"
       io.openshift.expose-services: ""
       io.openshift.tags: "acme,starter-ansible,starter,epel,ansible"
     command: "tail -f /dev/null"
     dev_overrides:
       environment:
         - "DEBUG=1"

registries: {}

  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx
