apiVersion: v1
kind: Template
metadata:
  name: systemd-httpd
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: systemd-httpd
    name: systemd-httpd
  spec:
    tags:
    - name: "systemd-httpd"
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "systemd-httpd" 
  spec:
    source:
      git:
        uri: https://github.com/RHsyseng/container-rhel-examples
      contextDir: "starter-systemd"
    strategy: 
      type: "Docker"
    output:
      to:
        kind: "ImageStreamTag"
        name: "systemd-httpd:latest"
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: systemd-httpd
    name: systemd-httpd
  spec:
    replicas: 1
    selector:
      app: systemd-httpd
      deploymentconfig: systemd-httpd
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
        labels:
          app: systemd-httpd
          deploymentconfig: systemd-httpd
      spec:
        containers:
        - image: systemd-httpd
          imagePullPolicy: Always
          name: systemd-httpd
          ports:
          - containerPort: 80
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /sys/fs/cgroup
            name: cgroup
          - mountPath: /run
            name: run
          - mountPath: /tmp
            name: tmp
          - mountPath: /var/log/httpd
            name: log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroup
        - emptyDir: {}
          name: run
        - emptyDir: {}
          name: tmp
        - emptyDir: {}
          name: log
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - systemd-httpd
        from:
          kind: ImageStreamTag
          name: systemd-httpd:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: systemd-httpd
    name: systemd-httpd
  spec:
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      deploymentconfig: systemd-httpd
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: systemd-httpd
    name: systemd-httpd
  spec:
    port:
      targetPort: 80-tcp
    to:
      kind: Service
      name: systemd-httpd