apiVersion: v1
kind: Template
metadata:
  name: glen-test-image
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 7
    labels:
      app: glen-test-image
    name: glen-test-image
  spec:
    replicas: 1
    selector:
      app: glen-test-image
      deploymentconfig: glen-test-image
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: glen-test-image
          deploymentconfig: glen-test-image
      spec:
        containers:
        - image: glen-test-image
          imagePullPolicy: Always
          name: glen-test-image
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - glen-test-image
        from:
          kind: ImageStreamTag
          name: glen-test-image:latest
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: glen-test-image
    name: glen-test-image
  spec:
    tags:
    - name: "glen-test-image"
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "glen-test-image"
  spec:
    source:
      git:
        uri: https://github.com/RHsyseng/container-rhel-examples
      contextDir: "glen-test-image"
    strategy: 
      type: "Docker"
    output:
      to:
        kind: "ImageStreamTag"
        name: "glen-test-image:latest"
    triggers:
    - generic:
        secret: b725254e6534fd70
      type: Generic
    - type: ConfigChange
