@Library('Utils')
import com.redhat.*

node {

    createDockerCfgJenkinsCredential {
        secretName = "containerzone"
    }

    stage('Start OpenShift Build') {
        openshiftBuild(buildConfig: "glen-test-image-ex-reg", showBuildLogs: 'true')
    }

    containerZoneScan {
        credentialsId = "containerzone"
        openShiftUri = "insecure://api.rhc4tp.openshift.com"
        imageName = "glen-test-image"
        imageTag = "1.0"
    }
}
