@Library('Utils')
import com.redhat.*

node {

    createDockerCfgJenkinsCredential {
        secretName = "ContainerZone"
    }

    stage('Start OpenShift Build') {
        openshiftBuild(buildConfig: "starter-arbitrary-uid-ex-reg", showBuildLogs: 'true')
    }

    containerZoneScan {
        credentialsId = "ContainerZone"
        openShiftUri = "insecure://api.rhc4tp.openshift.com"
        imageName = "starter-arbitrary-uid"
        imageTag = "1.0"
    }
}
