@Library('Utils')
import com.redhat.*

node {

    createDockerCfgJenkinsCredential {
        secretName = "containerzone"
    }

    stage('Start OpenShift Build') {
        openshiftBuild(buildConfig: "JenkinsCIDocker-ex-reg", showBuildLogs: 'true')
    }

    containerZoneScan {
        credentialsId = "containerzone"
        openShiftUri = "insecure://api.rhc4tp.openshift.com"
        imageName = "JenkinsCIDocker"
        imageTag = "1.0"
    }
}
